version: "3"

services:
  postgres_db:
    build: ./db
    container_name: postgres
    restart: always
    volumes:
      - /chargeflaskdata/postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TEST_DATABASE_NAME: ${TEST_DATABASE_NAME}
      SENTRY_DSN: ${SENTRY_DSN}
      SAML_SETTINGS: ${SAML_SETTINGS}

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - /chargeflaskdata/redis-data:/data
    expose:
      - "6379"

  huey_worker:
    build: .
    command: sh -c "python postgreswait.py && huey_consumer app.invitations.controllers.huey"
    volumes:
      - .:/chargeflask
    environment:
      APP_SECRET_KEY: ${APP_SECRET_KEY}
      SERVER_ENV: ${SERVER_ENV}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      CLIENT_URL: ${CLIENT_URL}
      SQLALCHEMY_DATABASE_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      SQLALCHEMY_TEST_DATABASE_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${TEST_DATABASE_NAME}
      REDIS_URL: ${REDIS_URL}
      SENTRY_DSN: ${SENTRY_DSN}
      SAML_SETTINGS: ${SAML_SETTINGS}
    links:
      - redis
      - postgres_db

  flask:
    build: .
    command: sh -c "python postgreswait.py && python run.py"
    volumes:
      - .:/chargeflask
    ports:
      - "5000:5000"
    environment:
      APP_SECRET_KEY: ${APP_SECRET_KEY}
      SERVER_ENV: ${SERVER_ENV}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      CLIENT_URL: ${CLIENT_URL}
      SQLALCHEMY_DATABASE_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      SQLALCHEMY_TEST_DATABASE_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${TEST_DATABASE_NAME}
      REDIS_URL: ${REDIS_URL}
      SENTRY_DSN: ${SENTRY_DSN}
      SAML_SETTINGS: ${SAML_SETTINGS}
    depends_on:
      - postgres_db
      - redis
